import Head from "next/head";
import FormPage from "@/components/formPage/formPage";
import NavBar from "@/components/navBar/navBar";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-[#FAF9F6] font-mont">
        <NavBar />
        <FormPage />
      </main>
    </>
  );
}
